# Generated by Django 5.0.2 on 2024-02-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0002_basemodel_changed_at_basemodel_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='place_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='tagline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='familyName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='givenName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='middleName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='prefix',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='suffix',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='namedtelephone',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='namedtelephone',
            name='value',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='addressLine',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='postalCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='weblink',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
