# Generated by Django 5.0.2 on 2024-02-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0003_alter_businessprofile_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullname',
            old_name='familyName',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='fullname',
            old_name='givenName',
            new_name='given_name',
        ),
        migrations.RenameField(
            model_name='fullname',
            old_name='middleName',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='postaladdress',
            old_name='addressLine',
            new_name='address_line',
        ),
    ]
