# Generated by Django 5.0.2 on 2024-02-27 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_profile', '0005_remove_businessprofile_telephones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='fellowship',
            field=models.ManyToManyField(blank=True, related_name='fellowship_skills', to='business_profile.skill'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='geoAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_profile.postaladdress'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='insurances',
            field=models.ManyToManyField(blank=True, to='business_profile.insurance'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='localities',
            field=models.ManyToManyField(blank=True, to='business_profile.locality'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='person_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_profile.fullname'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='service_skills', to='business_profile.skill'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='specialty',
            field=models.ManyToManyField(blank=True, related_name='specialty_skills', to='business_profile.skill'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='subspecialty',
            field=models.ManyToManyField(blank=True, related_name='subspecialty_skills', to='business_profile.skill'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
